### ISSUE TITLE
S3 bucket name char length exceeds 63 chars

### ISSUE THREAD

**Issue by mathewwallebos** [splunk/splunk-aws-gdi-toolkit#25]
CloudWatchMetrics-Firehose-Resources/cwMetricsToSplunk.yml

Each S3 resource bucket name exceeds the 63 char limit.
Cloudformation returns: 'Resource handler returned message: "Bucket name should be between 3 and 63 characters long" (RequestToken: ... '

For example:
  firehoseBacksplashBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-cwmetrics-${splunkEventType}-firehose-backsplash"

Sample BucketName:  123456789012-ap-southeast-2-cwmetrics-metric-firehose-backsplash
This is 64 char long.  Max char length is 63.

**Comment by preeves-splunk** [comment]
Hey @mathewwallebos, thanks for reporting this!  I just pushed this commit: https://github.com/splunk/splunk-aws-gdi-toolkit/commit/e366d0f2d0c274981e02b6289fb87068cef681e8 .  

Would you be able to try deploying the CloudFormation Template again just to make sure it resolves this issue?

**Comment by mathewwallebos** [comment]
nice work.  its fixed. thank you.
